version: "3.8"

services:
  discord-bot:
    container_name: wormhole-bot-dev
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: wormhole-bot:debug
    volumes:
      - .:/app
      - ssd-data:/mnt/ExtremeSSD/Wormhole/dev
    env_file:
      - .env_dev
    networks:
      - wormhole-network-dev
    ports:
      - "5679:5678"
    depends_on:
      - postgres
      - ollama
      - redis
    restart: always
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "run_discord.py"]

  postgres:
    image: postgres:latest
    container_name: wormhole-postgres-dev
    env_file:
      - .env_dev
    volumes:
      - /mnt/ExtremeSSD/Wormhole/dev/database/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wormhole-network-dev
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: wormhole-pgadmin-dev
    env_file:
      - .env_dev
    volumes:
      - /mnt/ExtremeSSD/Wormhole/dev/database/pgadmin:/var/lib/pgadmin
    networks:
      - wormhole-network-dev
    ports:
      - "5052:80"
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama
    container_name: ollama-dev
    volumes:
      - /mnt/ExtremeSSD/ollama:/root/.ollama
    ports:
      - "11435:11434"
    networks:
      - wormhole-network-dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ssh-chat:
    container_name: ssh-chat-dev
    env_file:
      - .env_dev
    build:
      dockerfile: ./docker/ssh-chat/Dockerfile.debug.yml
      context: .
    ports:
      - "2022:2022"
    restart: unless-stopped
    volumes:
      - ssd-data:/mnt/ExtremeSSD/Wormhole/dev
    networks:
      - wormhole-network-dev
    depends_on:
      - redis
    command: ["/usr/local/bin/ssh-chat", "-i", "/root/.ssh/id_ed25519_ssh_chat"]

  redis:
    image: redis:latest
    env_file:
      - .env_dev
    container_name: wormhole-redis-dev
    ports:
      - "6380:6380"
    command: ["redis-server", "--port", "6380"] 
    volumes:
      - /mnt/ExtremeSSD/Wormhole/dev/redis:/data
    networks:
      - wormhole-network-dev
    restart: always

networks:
  wormhole-network-dev:
    driver: bridge

volumes:
  ssd-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ExtremeSSD/Wormhole/dev
  ollama: