version: "3.8"

services:
  discord-bot-prod:
    container_name: wormhole-bot-prod
    build:
      context: .
      dockerfile: Dockerfile
    image: wormhole-bot:prod
    volumes:
      - .:/app
      - $HOME/Wormhole:/opt/wormhole/prod
    env_file:
      - .env
    networks:
      - wormhole-network-prod
    ports:
      - "5678:5679"
    depends_on:
      - postgres-prod
      - redis-prod
    restart: always
    command: ["python", "run_discord.py"]

  postgres-prod:
    image: postgres:latest
    container_name: wormhole-postgres-prod
    env_file:
      - .env
    volumes:
      - $HOME/Wormhole/database/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wormhole-network-prod
    ports:
      - "5434:5432"

  ssh-chat-prod:
    container_name: ssh-chat-prod
    env_file:
      - .env
    build:
      dockerfile: ./docker/ssh-chat/Dockerfile.prod.yml
      context: .
    ports:
      - "2023:2022"
    restart: unless-stopped
    volumes:
      - $HOME/Wormhole:/opt/wormhole/prod
    networks:
      - wormhole-network-prod
    depends_on:
      - redis-prod
    command: ["/usr/local/bin/ssh-chat", "-i", "/root/.ssh/id_ed25519_ssh_chat"]

  redis-prod:
    image: redis:latest
    env_file:
      - .env
    container_name: wormhole-redis-prod
    ports:
      - "6381:6381"
    command: ["redis-server", "--port", "6381"] 
    volumes:
      - $HOME/Wormhole/redis:/data
    networks:
      - wormhole-network-prod
    restart: always

networks:
  wormhole-network-prod:
    driver: bridge

volumes:
  wormhole-data-prod:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/Wormhole/