version: "3.8"

services:
  discord-bot-debug:
    container_name: wormhole-bot-debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: wormhole-bot:debug
    volumes:
      - .:/app
      - ssd-data-dev:/mnt/ExtremeSSD/Wormhole/dev
    env_file:
      - .env_dev
    networks:
      - wormhole-network-dev
    ports:
      - "5678:5678"
    depends_on:
      - postgres-debug
      - ollama
    restart: always
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "run_discord.py"]

  postgres-debug:
    image: postgres:latest
    container_name: wormhole-postgres-debug
    env_file:
      - .env_dev
    volumes:
      - /mnt/ExtremeSSD/Wormhole/dev/database/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wormhole-network-dev
    ports:
      - "5433:5432"

  pgadmin-debug:
    image: dpage/pgadmin4:latest
    container_name: wormhole-pgadmin-debug
    env_file:
      - .env_dev
    volumes:
      - /mnt/ExtremeSSD/Wormhole/dev/database/pgadmin:/var/lib/pgadmin
    networks:
      - wormhole-network-dev
    ports:
      - "5051:80"
    depends_on:
      - postgres-debug

  ollama:
    image: ollama/ollama
    container_name: ollama-debug
    volumes:
      - /mnt/ExtremeSSD/ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - wormhole-network-dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  wormhole-network-dev:
    driver: bridge

volumes:
  ssd-data-dev:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ExtremeSSD/Wormhole/dev
  ollama:
