version: "3.8"

services:
  discord-bot:
    container_name: wormhole-bot-dev
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: wormhole-bot:debug
    volumes:
      - .:/app
      - $HOME/Wormhole/dev:/opt/wormhole/dev
    env_file:
      - .env_dev
    networks:
      - wormhole-network-dev
    ports:
      - "5679:5678"
    depends_on:
      - postgres
      - redis
    restart: always
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "run_discord.py"]

  postgres:
    image: postgres:latest
    container_name: wormhole-postgres-dev
    env_file:
      - .env_dev
    volumes:
      - $HOME/Wormhole/dev/database/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wormhole-network-dev
    ports:
      - "5435:5432"

  ssh-chat:
    container_name: ssh-chat-dev
    env_file:
      - .env_dev
    build:
      dockerfile: ./docker/ssh-chat/Dockerfile.debug.yml
      context: .
    ports:
      - "2022:2022"
    restart: unless-stopped
    volumes:
      - $HOME/Wormhole/dev:/opt/wormhole/dev
    networks:
      - wormhole-network-dev
    depends_on:
      - redis
    command: ["/usr/local/bin/ssh-chat", "-i", "/root/.ssh/id_ed25519_ssh_chat"]

  redis:
    image: redis:latest
    env_file:
      - .env_dev
    container_name: wormhole-redis-dev
    ports:
      - "6380:6380"
    command: ["redis-server", "--port", "6380"] 
    volumes:
      - $HOME/Wormhole/dev/redis:/data
    networks:
      - wormhole-network-dev
    restart: always

networks:
  wormhole-network-dev:
    driver: bridge

volumes:
  wormhole-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/Wormhole/