FROM golang:alpine AS builder

ARG VERSION=v1.10

WORKDIR /usr/src/app

RUN apk add --no-cache git make openssh && \
    git clone https://github.com/shazow/ssh-chat.git . && \
    git checkout ${VERSION} && \
    make build

FROM alpine

RUN apk add --no-cache openssh
RUN mkdir /root/.ssh
WORKDIR /root/.ssh
RUN ssh-keygen -t ed25519 -f id_ed25519_ssh_chat -N ""

WORKDIR /usr/local/bin

COPY --from=builder /usr/src/app/ssh-chat .
RUN chmod +x ssh-chat
CMD ["/usr/local/bin/ssh-chat", "-i", "/root/.ssh/id_ed25519_ssh_chat"]