FROM golang:alpine AS builder

WORKDIR /

RUN apk add --no-cache git make openssh
COPY ./Wormhole-ssh-chat /Wormhole-ssh-chat

WORKDIR /Wormhole-ssh-chat
RUN make build

FROM alpine

RUN apk add --no-cache openssh
RUN mkdir /root/.ssh
WORKDIR /root/.ssh
RUN ssh-keygen -t ed25519 -f id_ed25519_ssh_chat -N ""

WORKDIR /usr/local/bin

COPY --from=builder /Wormhole-ssh-chat .
RUN chmod +x ssh-chat
CMD ["/usr/local/bin/ssh-chat", "-i", "/root/.ssh/id_ed25519_ssh_chat"]